- name: Remove enterprise subscription list.
  file:
    path: "/etc/apt/sources.list.d/{{ item }}"
    state: absent
  with_items:
    - pve-enterprise.list.dpkg-dist
    - pve-enterprise.list
  tags:
    - apt

- name: Create no subscription update list.
  copy:
    dest: /etc/apt/sources.list.d/pve-no-subscription.list
    content:  deb http://download.proxmox.com/debian/pve buster pve-no-subscription
  tags:
    - apt

- name: Configure sysctl.
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ pve_sysctl }}"
  tags:
    - sysctl

- name: Download templates.
  command: "pveam download local {{ item }}"
  args:
    creates: /var/lib/vz/template/cache/{{ item }}
  with_items: "{{ pve_templates }}"
  tags:
    - templates

- name: Postfix setup.
  include_tasks: postfix.yml
  tags:
    - postfix
  when:
    - pve_mail_relay_host is defined
    - pve_mail_relay_port is defined
    - pve_mail_relay_username is defined
    - pve_mail_relay_password is defined
    - pve_mail_default_recipient is defined

- name: vzdump config.
  include_tasks: vzdump.yml
  tags:
    - vzdump

- name: Ldap setup.
  include_tasks: ldap.yml
  with_items: "{{ pve_ldap_domains }}"
  tags:
    - ldap

- name: fstrim.
  include_tasks: fstrim.yml
  tags:
    - fstrim

- name: lxc config.
  include_tasks: lxc_config.yml
  tags:
    - lxc_config
  with_items: "{{ pve_lxc_config }}"

- name: Enable backports
  copy:
    dest: /etc/apt/sources.list.d/backports.list
    content: |
      deb http://ftp.de.debian.org/debian buster-backports main

- name: Configure resolv.conf
  copy:
    dest: /etc/resolv.conf
    content: |
      # managed by Ansible tobias_richter.proxmox role
      domain {{ pve_dns_domain }}
      search {{ pve_dns_domain }}
      nameserver {{ pve_nameserver }}

- block:

  - name: touch influxdb status.cfg first.
    file:
      path: /etc/pve/status.cfg
      state: touch


  - name: Configure influxdb in status.cfg
    copy:
      dest: /etc/pve/status.cfg
      content: |
        # managed by Ansible tobias_richter.proxmox role
        influxdb:
          server {{ pve_influxdb_host }}
          port {{ pve_influxdb_port }}

  when:
    - pve_influxdb_port is defined
    - pve_influxdb_host is defined