- name: Install packages for postfix
  apt:
    name: libsasl2-modules

- name: Configure postfix
  blockinfile:
    path: /etc/postfix/main.cf
    block: |
      # sets relay server
      relayhost = [{{ pve_mail_relay_host }}]:{{ pve_mail_relay_port }}

      #  use tls
      smtp_use_tls = {{ pve_mail_smtp_use_tls }}

      # use sasl when authenticating to foreign SMTP servers
      smtp_sasl_auth_enable = yes

      # path to password map file
      smtp_sasl_password_maps = hash:/etc/postfix/sasl/passwd

      # list of CAs to trust when verifying server certificate
      #smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt

      # eliminates default security options which are incompatible with gmail
      smtp_sasl_security_options = noanonymous
      smtp_sasl_tls_security_options = noanonymous

      header_size_limit = 4096000

      # needed by tls
      smtp_tls_wrappermode = {{ pve_mail_smtp_tls_wrappermode }}
      smtp_tls_security_level = encrypt

      # rewrite sender
      sender_canonical_classes = envelope_sender, header_sender
      sender_canonical_maps =  regexp:/etc/postfix/sender_canonical_maps
      smtp_header_checks = regexp:/etc/postfix/header_check

  register: __postfix_config
  notify:
    - restart postfix

- name: Remove duplicate relayhost.
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: ^relayhost\s*=\s*$
    line: "# relayhost ="

- name: Configure sender_canonical_maps
  blockinfile:
    path: /etc/postfix/sender_canonical_maps
    create: yes
    block: |
      /.+/    pve@{{ pve_mail_domain }}
  notify:
    - restart postfix

- name: Configure header_check
  blockinfile:
    path: /etc/postfix/header_check
    create: yes
    block: |
      /From:.*/ REPLACE From: pve@{{ pve_mail_domain }}
  notify:
    - restart postfix

- name: Fix permissions
  file:
    path: /etc/postfix/sasl
    state: directory
    group: postfix
    mode: g=rwX

- name: Provide relay server credentials.
  copy:
    dest: "/etc/postfix/sasl/passwd"
    content: "[{{ pve_mail_relay_host }}]:{{ pve_mail_relay_port }}  {{ pve_mail_relay_username }}:{{ pve_mail_relay_password }}"
    owner: root
    group: root
  notify:
    - restart postfix

- name: Create passwd # noqa 503
  command: postmap /etc/postfix/sasl/passwd
  when: __postfix_config.changed
  notify:
    - restart postfix

- name: Change ownership
  file:
    path: /etc/postfix/sasl/passwd
    owner: root
    group: root
  notify:
    - restart postfix