- name: ensure backup tmp dir exists
  file:
    path: "{{ pve_vzdump_tmpdir }}"
    state: directory

- name: Configure vzdump
  blockinfile:
    path: /etc/vzdump.conf
    block: |
      tmpdir: {{ pve_vzdump_tmpdir }}
      mailto: {{ pve_mail_default_recipient | mandatory }}
    mode: 0644
  notify:
    - restart pveproxy